# Generated by Django 5.0.6 on 2024-06-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='file',
            new_name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='pdf',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='nouns',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='verbs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
